export type LibraryMode = "Explainer" | "Repetition";

export type LibrarySubtopic = {
  id: string;
  title: string;
  duration: string;
};

export type LibraryTopic = {
  id: string;
  title: string;
  description: string;
  courseType: "Combined" | "Triple";
  tier: "Foundation" | "Higher";
  examBoard: "AQA" | "Edexcel" | "OCR";
  subtopics: LibrarySubtopic[];
};

export type LibrarySubject = {
  id: string;
  name: string;
  icon: string;
  accent: string;
  gradient: [string, string];
  topics: LibraryTopic[];
};

const minutes = (value: number) => `${value} min`;

export const STUDYCAST_LIBRARY: LibrarySubject[] = [
  {
    id: "biology",
    name: "Biology",
    icon: "🧬",
    accent: "#2dd4bf",
    gradient: ["rgba(45,212,191,0.18)", "rgba(13,148,136,0.45)"],
    topics: [
      {
        id: "bio-cell-biology",
        title: "Cell Biology",
        description: "Everything from microscopes to mitosis with quick recall hooks for each process.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "bio-cell-structure", title: "1.1 Cell structure & organelles", duration: minutes(6) },
          { id: "bio-cell-microscopy", title: "1.2 Microscopy & magnification", duration: minutes(7) },
          { id: "bio-cell-prokaryotic", title: "1.3 Prokaryotic vs eukaryotic cells", duration: minutes(6) },
          { id: "bio-cell-division", title: "1.4 Cell division & the cell cycle", duration: minutes(8) },
          { id: "bio-cell-stem", title: "1.5 Stem cells & differentiation", duration: minutes(6) },
          { id: "bio-cell-transport", title: "1.6 Diffusion, osmosis & active transport", duration: minutes(7) },
          { id: "bio-cell-surface", title: "1.7 Surface area to volume ratio", duration: minutes(5) },
          { id: "bio-cell-single", title: "1.8 Transport in single-celled organisms", duration: minutes(5) },
          { id: "bio-cell-specialisation", title: "1.9 Cell specialisation", duration: minutes(6) },
          { id: "bio-cell-practical", title: "1.10 Practical: Microscopy & osmosis in plants", duration: minutes(9) },
        ],
      },
      {
        id: "bio-organisation",
        title: "Organisation",
        description: "Digestive, circulatory and plant transport systems with practical walkthroughs.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "bio-org-digestive", title: "2.1 The digestive system", duration: minutes(6) },
          { id: "bio-org-enzymes", title: "2.2 Enzymes & factors affecting enzyme action", duration: minutes(7) },
          { id: "bio-org-circulatory", title: "2.3 The circulatory system", duration: minutes(6) },
          { id: "bio-org-blood", title: "2.4 Blood composition & the heart", duration: minutes(7) },
          { id: "bio-org-gas", title: "2.5 Gas exchange in the lungs", duration: minutes(6) },
          { id: "bio-org-plant", title: "2.6 Plant tissues & transpiration", duration: minutes(6) },
          { id: "bio-org-transport", title: "2.7 The transport of water & minerals", duration: minutes(6) },
          { id: "bio-org-leaf", title: "2.8 The leaf & photosynthesis link", duration: minutes(5) },
          { id: "bio-org-food-tests", title: "2.9 Practical: Food tests", duration: minutes(8) },
          { id: "bio-org-enzymes-prac", title: "2.10 Practical: Effect of temperature on enzymes", duration: minutes(8) },
        ],
      },
      {
        id: "bio-infection",
        title: "Infection & Response",
        description: "Immune system responses, drug development and plant disease defences.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "bio-inf-disease", title: "3.1 Communicable diseases", duration: minutes(6) },
          { id: "bio-inf-defence", title: "3.2 Non-specific defence systems", duration: minutes(6) },
          { id: "bio-inf-immune", title: "3.3 The immune system & white blood cells", duration: minutes(6) },
          { id: "bio-inf-vaccination", title: "3.4 Vaccination & immunisation", duration: minutes(6) },
          { id: "bio-inf-antibiotics", title: "3.5 Antibiotics & antibiotic resistance", duration: minutes(6) },
          { id: "bio-inf-drugs", title: "3.6 Drug development & testing", duration: minutes(6) },
          { id: "bio-inf-viral", title: "3.7 Viral diseases (HIV, measles)", duration: minutes(6) },
          { id: "bio-inf-bacterial", title: "3.8 Bacterial diseases (salmonella)", duration: minutes(5) },
          { id: "bio-inf-plant", title: "3.9 Plant diseases & defences", duration: minutes(6) },
          { id: "bio-inf-practical", title: "3.10 Practical: Growing microorganisms", duration: minutes(8) },
        ],
      },
      {
        id: "bio-bioenergetics",
        title: "Bioenergetics",
        description: "Photosynthesis, respiration and the energy transfers that link them.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "bio-bioequations", title: "4.1 Photosynthesis word & symbol equation", duration: minutes(5) },
          { id: "bio-biolimiting", title: "4.2 Limiting factors of photosynthesis", duration: minutes(6) },
          { id: "bio-biouse", title: "4.3 Use of glucose in plants", duration: minutes(6) },
          { id: "bio-biorespiration", title: "4.4 Aerobic & anaerobic respiration", duration: minutes(6) },
          { id: "bio-biomitochondria", title: "4.5 The role of mitochondria", duration: minutes(5) },
          { id: "bio-bioenergy", title: "4.6 Energy transfer & metabolism", duration: minutes(6) },
          { id: "bio-bioexercise", title: "4.7 Exercise and respiration", duration: minutes(6) },
          { id: "bio-biooxygen", title: "4.8 Oxygen debt & recovery", duration: minutes(5) },
          { id: "bio-biophotosyn-prac", title: "4.9 Practical: Investigating photosynthesis", duration: minutes(8) },
          { id: "bio-bioresp-prac", title: "4.10 Practical: Measuring respiration rate", duration: minutes(8) },
        ],
      },
      {
        id: "bio-homeostasis",
        title: "Homeostasis & Response",
        description: "Control systems, hormones and reflexes with revision-friendly case studies.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "bio-home-nervous", title: "5.1 The nervous system & reflex actions", duration: minutes(6) },
          { id: "bio-home-synapses", title: "5.2 Synapses & neurotransmitters", duration: minutes(6) },
          { id: "bio-home-endocrine", title: "5.3 Endocrine system & hormones", duration: minutes(6) },
          { id: "bio-home-glucose", title: "5.4 Blood glucose control", duration: minutes(6) },
          { id: "bio-home-diabetes", title: "5.5 Diabetes", duration: minutes(5) },
          { id: "bio-home-temperature", title: "5.6 Control of body temperature", duration: minutes(6) },
          { id: "bio-home-menstrual", title: "5.7 The menstrual cycle", duration: minutes(6) },
          { id: "bio-home-contraception", title: "5.8 Contraception methods", duration: minutes(6) },
          { id: "bio-home-brain", title: "5.9 The brain & eye structure", duration: minutes(7) },
          { id: "bio-home-practical", title: "5.10 Practical: Reaction time investigation", duration: minutes(8) },
        ],
      },
      {
        id: "bio-inheritance",
        title: "Inheritance, Variation & Evolution",
        description: "DNA, genetics, selective breeding and speciation in context.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "bio-inh-dna", title: "6.1 DNA structure & the genome", duration: minutes(6) },
          { id: "bio-inh-protein", title: "6.2 Protein synthesis", duration: minutes(7) },
          { id: "bio-inh-mutations", title: "6.3 Mutations & genetic disorders", duration: minutes(6) },
          { id: "bio-inh-reproduction", title: "6.4 Sexual & asexual reproduction", duration: minutes(6) },
          { id: "bio-inh-meiosis", title: "6.5 Meiosis & gametes", duration: minutes(6) },
          { id: "bio-inh-genetics", title: "6.6 Genetic inheritance & Punnett squares", duration: minutes(7) },
          { id: "bio-inh-variation", title: "6.7 Variation & natural selection", duration: minutes(6) },
          { id: "bio-inh-evolution", title: "6.8 Evolution & evidence for evolution", duration: minutes(6) },
          { id: "bio-inh-selective", title: "6.9 Selective breeding & genetic engineering", duration: minutes(6) },
          { id: "bio-inh-classification", title: "6.10 Classification & speciation", duration: minutes(6) },
        ],
      },
      {
        id: "bio-ecology",
        title: "Ecology",
        description: "Ecosystems, cycles and human impact with fieldwork-ready examples.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "bio-eco-organisation", title: "7.1 Levels of organisation & ecosystems", duration: minutes(6) },
          { id: "bio-eco-factors", title: "7.2 Abiotic & biotic factors", duration: minutes(6) },
          { id: "bio-eco-adaptations", title: "7.3 Adaptations in plants & animals", duration: minutes(6) },
          { id: "bio-eco-food-chains", title: "7.4 Food chains & trophic levels", duration: minutes(6) },
          { id: "bio-eco-decomposers", title: "7.5 Decomposers & decay", duration: minutes(5) },
          { id: "bio-eco-cycles", title: "7.6 Carbon & water cycles", duration: minutes(6) },
          { id: "bio-eco-biodiversity", title: "7.7 Biodiversity", duration: minutes(5) },
          { id: "bio-eco-human", title: "7.8 Human impacts on ecosystems", duration: minutes(6) },
          { id: "bio-eco-deforestation", title: "7.9 Deforestation & global warming", duration: minutes(6) },
          { id: "bio-eco-practical", title: "7.10 Practical: Field sampling & quadrats", duration: minutes(8) },
        ],
      },
    ],
  },
  {
    id: "chemistry",
    name: "Chemistry",
    icon: "⚗️",
    accent: "#f97316",
    gradient: ["rgba(249,115,22,0.16)", "rgba(234,88,12,0.45)"],
    topics: [
      {
        id: "chem-atomic-structure",
        title: "Atomic Structure & Periodic Table",
        description: "Model of the atom, isotopes and group trends explained simply.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "chem-atomic-history", title: "1.1 History of the atomic model", duration: minutes(6) },
          { id: "chem-atomic-subatomic", title: "1.2 Subatomic particles", duration: minutes(6) },
          { id: "chem-atomic-isotopes", title: "1.3 Isotopes & relative atomic mass", duration: minutes(5) },
          { id: "chem-atomic-electronic", title: "1.4 Electronic configuration", duration: minutes(6) },
          { id: "chem-atomic-layout", title: "1.5 The periodic table layout", duration: minutes(5) },
          { id: "chem-atomic-metals", title: "1.6 Metals vs non-metals", duration: minutes(5) },
          { id: "chem-atomic-group1", title: "1.7 Group 1 properties", duration: minutes(5) },
          { id: "chem-atomic-group7", title: "1.8 Group 7 properties", duration: minutes(5) },
          { id: "chem-atomic-group0", title: "1.9 Group 0 noble gases", duration: minutes(5) },
          { id: "chem-atomic-transition", title: "1.10 Transition metals", duration: minutes(6) },
        ],
      },
      {
        id: "chem-bonding",
        title: "Bonding & Properties of Matter",
        description: "Compare ionic, covalent and metallic bonding with structure deep dives.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "chem-bonding-ionic", title: "2.1 Ionic bonding & compounds", duration: minutes(6) },
          { id: "chem-bonding-covalent", title: "2.2 Covalent bonding", duration: minutes(6) },
          { id: "chem-bonding-metallic", title: "2.3 Metallic bonding", duration: minutes(5) },
          { id: "chem-bonding-giant-ionic", title: "2.4 Giant ionic lattices", duration: minutes(6) },
          { id: "chem-bonding-simple", title: "2.5 Simple molecules", duration: minutes(5) },
          { id: "chem-bonding-polymers", title: "2.6 Polymers & giant covalent structures", duration: minutes(6) },
          { id: "chem-bonding-graphite", title: "2.7 Graphite & graphene", duration: minutes(6) },
          { id: "chem-bonding-fullerenes", title: "2.8 Fullerenes & nanoparticles", duration: minutes(6) },
          { id: "chem-bonding-states", title: "2.9 States of matter & changes of state", duration: minutes(5) },
          { id: "chem-bonding-properties", title: "2.10 Properties & melting points", duration: minutes(6) },
        ],
      },
      {
        id: "chem-quantitative",
        title: "Quantitative Chemistry",
        description: "Moles, concentration and yield with calculator-ready worked examples.",
        courseType: "Combined",
        tier: "Higher",
        examBoard: "AQA",
        subtopics: [
          { id: "chem-quant-relative", title: "3.1 Relative formula mass", duration: minutes(6) },
          { id: "chem-quant-conservation", title: "3.2 Conservation of mass", duration: minutes(5) },
          { id: "chem-quant-moles", title: "3.3 Moles & Avogadro’s number", duration: minutes(6) },
          { id: "chem-quant-equations", title: "3.4 Using moles in equations", duration: minutes(6) },
          { id: "chem-quant-concentration", title: "3.5 Concentration in solutions", duration: minutes(6) },
          { id: "chem-quant-limiting", title: "3.6 Limiting reactants", duration: minutes(6) },
          { id: "chem-quant-yield", title: "3.7 Percentage yield", duration: minutes(6) },
          { id: "chem-quant-atom-economy", title: "3.8 Atom economy", duration: minutes(6) },
          { id: "chem-quant-gas", title: "3.9 Gas volume calculations", duration: minutes(7) },
          { id: "chem-quant-titrations", title: "3.10 Practical: Titrations", duration: minutes(8) },
        ],
      },
      {
        id: "chem-chemical-changes",
        title: "Chemical Changes",
        description: "Redox, electrolysis and acid reactions linked to exam-style responses.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "chem-changes-reactivity", title: "4.1 Reactivity series & metal extraction", duration: minutes(6) },
          { id: "chem-changes-displacement", title: "4.2 Displacement reactions", duration: minutes(5) },
          { id: "chem-changes-redox", title: "4.3 Redox reactions", duration: minutes(6) },
          { id: "chem-changes-electrolysis", title: "4.4 Electrolysis principles", duration: minutes(6) },
          { id: "chem-changes-molten", title: "4.5 Electrolysis of molten compounds", duration: minutes(6) },
          { id: "chem-changes-solutions", title: "4.6 Electrolysis of solutions", duration: minutes(6) },
          { id: "chem-changes-aluminium", title: "4.7 Extraction of aluminium", duration: minutes(5) },
          { id: "chem-changes-acids", title: "4.8 Reactions of acids with metals", duration: minutes(5) },
          { id: "chem-changes-neutralisation", title: "4.9 Neutralisation & salt formation", duration: minutes(6) },
          { id: "chem-changes-practical", title: "4.10 Practical: Electrolysis experiment", duration: minutes(8) },
        ],
      },
      {
        id: "chem-energy",
        title: "Energy Changes",
        description: "Exothermic vs endothermic reactions and fuel cell technology decoded.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "chem-energy-exothermic", title: "5.1 Exothermic & endothermic reactions", duration: minutes(6) },
          { id: "chem-energy-profiles", title: "5.2 Reaction profiles", duration: minutes(5) },
          { id: "chem-energy-bond", title: "5.3 Bond energy calculations", duration: minutes(7) },
          { id: "chem-energy-conservation", title: "5.4 Energy conservation", duration: minutes(5) },
          { id: "chem-energy-practical", title: "5.5 Practical: Temperature change reactions", duration: minutes(7) },
          { id: "chem-energy-cells", title: "5.6 Cells & batteries", duration: minutes(6) },
          { id: "chem-energy-fuel-cells", title: "5.7 Fuel cells & hydrogen", duration: minutes(6) },
          { id: "chem-energy-advantages", title: "5.8 Advantages & disadvantages of fuel cells", duration: minutes(6) },
          { id: "chem-energy-efficiency", title: "5.9 Efficiency in energy changes", duration: minutes(5) },
          { id: "chem-energy-transfer", title: "5.10 Energy transfer in reactions", duration: minutes(6) },
        ],
      },
      {
        id: "chem-rate-extent",
        title: "Rate & Extent of Chemical Change",
        description: "Collision theory, equilibria and industrial optimisation strategies.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "chem-rate-measuring", title: "6.1 Measuring rate of reaction", duration: minutes(6) },
          { id: "chem-rate-collision", title: "6.2 Collision theory", duration: minutes(5) },
          { id: "chem-rate-factors", title: "6.3 Temperature, concentration, surface area, catalysts", duration: minutes(6) },
          { id: "chem-rate-reversible", title: "6.4 Reversible reactions", duration: minutes(5) },
          { id: "chem-rate-equilibrium", title: "6.5 Equilibrium & Le Chatelier’s principle", duration: minutes(6) },
          { id: "chem-rate-practical", title: "6.6 Practical: Rate of reaction using marble chips", duration: minutes(7) },
          { id: "chem-rate-catalysts", title: "6.7 Catalysts in industry", duration: minutes(5) },
          { id: "chem-rate-endoexo", title: "6.8 Endo/exo in equilibrium", duration: minutes(5) },
          { id: "chem-rate-energy-profile", title: "6.9 Energy profile in reversible reactions", duration: minutes(5) },
          { id: "chem-rate-industrial", title: "6.10 Industrial applications", duration: minutes(6) },
        ],
      },
      {
        id: "chem-organic",
        title: "Organic Chemistry",
        description: "Hydrocarbons, polymers and functional groups with practical examples.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "chem-organic-crude", title: "7.1 Crude oil & fractional distillation", duration: minutes(6) },
          { id: "chem-organic-alkanes", title: "7.2 Alkanes & alkenes", duration: minutes(6) },
          { id: "chem-organic-combustion", title: "7.3 Combustion & testing for alkenes", duration: minutes(5) },
          { id: "chem-organic-alcohols", title: "7.4 Alcohols & carboxylic acids", duration: minutes(6) },
          { id: "chem-organic-esters", title: "7.5 Esters & their uses", duration: minutes(5) },
          { id: "chem-organic-addition", title: "7.6 Addition polymerisation", duration: minutes(6) },
          { id: "chem-organic-condensation", title: "7.7 Condensation polymerisation", duration: minutes(6) },
          { id: "chem-organic-dna", title: "7.8 DNA structure as a polymer", duration: minutes(5) },
          { id: "chem-organic-distillation", title: "7.9 Practical: Distillation", duration: minutes(7) },
          { id: "chem-organic-cracking", title: "7.10 Cracking hydrocarbons", duration: minutes(6) },
        ],
      },
      {
        id: "chem-analysis",
        title: "Chemical Analysis",
        description: "Identify unknowns with chromatography, flame tests and spectroscopy.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "chem-analysis-chromatography", title: "8.1 Chromatography principles", duration: minutes(6) },
          { id: "chem-analysis-pure", title: "8.2 Identifying pure substances", duration: minutes(5) },
          { id: "chem-analysis-gas", title: "8.3 Gas tests (H₂, O₂, CO₂, Cl₂)", duration: minutes(5) },
          { id: "chem-analysis-flame", title: "8.4 Flame tests for ions", duration: minutes(5) },
          { id: "chem-analysis-precipitation", title: "8.5 Precipitation reactions for ions", duration: minutes(6) },
          { id: "chem-analysis-instrumental", title: "8.6 Instrumental analysis introduction", duration: minutes(6) },
          { id: "chem-analysis-emission", title: "8.7 Flame emission spectroscopy", duration: minutes(6) },
          { id: "chem-analysis-unknown", title: "8.8 Identifying unknown compounds", duration: minutes(6) },
          { id: "chem-analysis-practical", title: "8.9 Practical: Chromatography experiment", duration: minutes(7) },
          { id: "chem-analysis-accuracy", title: "8.10 Accuracy & reliability in analysis", duration: minutes(6) },
        ],
      },
      {
        id: "chem-atmosphere",
        title: "Chemistry of the Atmosphere",
        description: "Evolution of Earth’s atmosphere and climate change evidence.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "chem-atmos-evolution", title: "9.1 Evolution of the atmosphere", duration: minutes(6) },
          { id: "chem-atmos-early", title: "9.2 Composition of early atmosphere", duration: minutes(5) },
          { id: "chem-atmos-greenhouse", title: "9.3 Greenhouse gases", duration: minutes(5) },
          { id: "chem-atmos-climate", title: "9.4 Climate change & carbon footprint", duration: minutes(6) },
          { id: "chem-atmos-combustion", title: "9.5 Combustion & air pollution", duration: minutes(5) },
          { id: "chem-atmos-acid", title: "9.6 Acid rain & effects", duration: minutes(5) },
          { id: "chem-atmos-evidence", title: "9.7 Global warming evidence", duration: minutes(5) },
          { id: "chem-atmos-human", title: "9.8 Human influence", duration: minutes(5) },
          { id: "chem-atmos-carbon", title: "9.9 Carbon cycle", duration: minutes(5) },
          { id: "chem-atmos-reducing", title: "9.10 Reducing emissions", duration: minutes(5) },
        ],
      },
      {
        id: "chem-using-resources",
        title: "Using Resources",
        description: "Sustainability, life-cycle assessments and the Haber process.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "chem-resources-finite", title: "10.1 Finite vs renewable resources", duration: minutes(5) },
          { id: "chem-resources-water", title: "10.2 Water treatment", duration: minutes(6) },
          { id: "chem-resources-lca", title: "10.3 Life cycle assessments", duration: minutes(6) },
          { id: "chem-resources-recycling", title: "10.4 Recycling & sustainability", duration: minutes(5) },
          { id: "chem-resources-ores", title: "10.5 Extracting metals from ores", duration: minutes(6) },
          { id: "chem-resources-corrosion", title: "10.6 Corrosion & prevention", duration: minutes(5) },
          { id: "chem-resources-alloys", title: "10.7 Alloys & composites", duration: minutes(6) },
          { id: "chem-resources-materials", title: "10.8 Glass, ceramics & polymers", duration: minutes(6) },
          { id: "chem-resources-haber", title: "10.9 Haber process", duration: minutes(6) },
          { id: "chem-resources-fertilisers", title: "10.10 Using fertilisers & NPK", duration: minutes(6) },
        ],
      },
    ],
  },
  {
    id: "physics",
    name: "Physics",
    icon: "⚙️",
    accent: "#38bdf8",
    gradient: ["rgba(56,189,248,0.16)", "rgba(14,165,233,0.45)"],
    topics: [
      {
        id: "phys-energy",
        title: "Energy",
        description: "Energy stores, transfers and national resources with visual mnemonics.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "OCR",
        subtopics: [
          { id: "phys-energy-stores", title: "1.1 Energy Stores & Systems", duration: minutes(6) },
          { id: "phys-energy-transfer-examples", title: "1.2 Energy Transfer Examples", duration: minutes(5) },
          { id: "phys-energy-kinetic", title: "1.3 Kinetic Energy", duration: minutes(5) },
          { id: "phys-energy-gpe", title: "1.4 Gravitational Potential Energy & Gravity", duration: minutes(6) },
          { id: "phys-energy-ke-gpe", title: "1.5 Transfer Between KE & GPE", duration: minutes(5) },
          { id: "phys-energy-shc", title: "1.6 Specific Heat Capacity", duration: minutes(6) },
          { id: "phys-energy-conservation", title: "1.7 Conservation of Energy", duration: minutes(5) },
          { id: "phys-energy-conduction", title: "1.8 Conduction, Convection & Radiation", duration: minutes(6) },
          { id: "phys-energy-unwanted", title: "1.9 Reducing Unwanted Energy Transfers", duration: minutes(5) },
          { id: "phys-energy-power", title: "1.10 Power & Work Done", duration: minutes(6) },
          { id: "phys-energy-efficiency", title: "1.11 Efficiency", duration: minutes(5) },
          { id: "phys-energy-resources-intro", title: "1.12 Energy Resources Introduction", duration: minutes(5) },
          { id: "phys-energy-fossil", title: "1.13 Fossil Fuels & Nuclear Energy", duration: minutes(6) },
          { id: "phys-energy-wind", title: "1.14 Wind & Solar", duration: minutes(5) },
          { id: "phys-energy-geothermal", title: "1.15 Geothermal Power", duration: minutes(5) },
          { id: "phys-energy-biofuels", title: "1.16 Biofuels", duration: minutes(5) },
          { id: "phys-energy-hydro", title: "1.17 Hydroelectricity & Tidal Barrages", duration: minutes(6) },
        ],
      },
      {
        id: "phys-electricity",
        title: "Electricity",
        description: "Circuits, the National Grid and safety features made memorable.",
        courseType: "Triple",
        tier: "Higher",
        examBoard: "AQA",
        subtopics: [
          { id: "phys-elec-intro", title: "2.1 Circuits Introduction", duration: minutes(5) },
          { id: "phys-elec-vir", title: "2.2 V = IR Equation & I-V Graphs", duration: minutes(6) },
          { id: "phys-elec-charge", title: "2.3 Charge, Current & Time", duration: minutes(5) },
          { id: "phys-elec-components", title: "2.4 Components", duration: minutes(5) },
          { id: "phys-elec-series", title: "2.5 Series Circuits", duration: minutes(6) },
          { id: "phys-elec-parallel", title: "2.6 Parallel Circuits", duration: minutes(6) },
          { id: "phys-elec-energy", title: "2.7 Energy & Power Formulas", duration: minutes(6) },
          { id: "phys-elec-grid", title: "2.8 National Grid", duration: minutes(5) },
          { id: "phys-elec-acdc", title: "2.9 AC & DC Current", duration: minutes(5) },
          { id: "phys-elec-plugs", title: "2.10 Plugs & Wires", duration: minutes(5) },
          { id: "phys-elec-fuses", title: "2.11 Fuses & Earthing", duration: minutes(5) },
          { id: "phys-elec-static", title: "2.12 Static Electricity", duration: minutes(6) },
          { id: "phys-elec-fields", title: "2.13 Electric Fields", duration: minutes(6) },
        ],
      },
      {
        id: "phys-particle-model",
        title: "Particle Model of Matter",
        description: "Density, specific latent heat and gas pressure questions demystified.",
        courseType: "Combined",
        tier: "Higher",
        examBoard: "Edexcel",
        subtopics: [
          { id: "phys-particle-model", title: "3.1 Particle Model & States of Matter", duration: minutes(5) },
          { id: "phys-particle-density", title: "3.2 Density", duration: minutes(5) },
          { id: "phys-particle-latent", title: "3.3 Specific Latent Heat", duration: minutes(6) },
          { id: "phys-particle-factors", title: "3.4 Factors Affecting Gas Pressure", duration: minutes(6) },
          { id: "phys-particle-pressure-volume", title: "3.5 Pressure & Volume (PV = Constant)", duration: minutes(6) },
        ],
      },
      {
        id: "phys-atomic",
        title: "Atomic Structure",
        description: "Development of the atom, radioactive decay and nuclear processes.",
        courseType: "Triple",
        tier: "Higher",
        examBoard: "OCR",
        subtopics: [
          { id: "phys-atomic-history", title: "4.1 Development of the Model of the Atom", duration: minutes(6) },
          { id: "phys-atomic-structure", title: "4.2 Atomic Structure, Isotopes & Electron Shells", duration: minutes(6) },
          { id: "phys-atomic-radiation", title: "4.3 Alpha, Beta & Gamma Radiation", duration: minutes(6) },
          { id: "phys-atomic-decay", title: "4.4 Nuclear Decay Equations", duration: minutes(6) },
          { id: "phys-atomic-half-life", title: "4.5 Radioactive Decay & Half-life", duration: minutes(6) },
          { id: "phys-atomic-harmful", title: "4.6 Why Radiation is Harmful", duration: minutes(5) },
          { id: "phys-atomic-medicine", title: "4.7 Using Radiation in Medicine", duration: minutes(6) },
          { id: "phys-atomic-fission", title: "4.8 Nuclear Fission", duration: minutes(6) },
          { id: "phys-atomic-fusion", title: "4.9 Nuclear Fusion", duration: minutes(6) },
        ],
      },
      {
        id: "phys-forces",
        title: "Forces",
        description: "Vectors, motion and momentum with step-by-step worked examples.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "phys-forces-contact", title: "5.1 Contact & Non-contact Forces", duration: minutes(5) },
          { id: "phys-forces-scalar", title: "5.2 Scalar & Vector Quantities", duration: minutes(5) },
          { id: "phys-forces-freebody", title: "5.3 Free Body Diagrams & Resultant Forces", duration: minutes(6) },
          { id: "phys-forces-resolving", title: "5.4 Resolving Vectors & Scale Drawings", duration: minutes(6) },
          { id: "phys-forces-elasticity", title: "5.5 Elasticity, Spring Constant & Hooke's Law", duration: minutes(6) },
          { id: "phys-forces-elastic-energy", title: "5.6 Elastic Potential Energy", duration: minutes(6) },
          { id: "phys-forces-moments1", title: "5.7 Moments 1", duration: minutes(5) },
          { id: "phys-forces-moments2", title: "5.8 Moments 2", duration: minutes(5) },
          { id: "phys-forces-pressure", title: "5.9 Pressure", duration: minutes(5) },
          { id: "phys-forces-liquid", title: "5.10 Liquid Pressure & Upthrust", duration: minutes(5) },
          { id: "phys-forces-atmospheric", title: "5.11 Atmospheric Pressure", duration: minutes(5) },
          { id: "phys-forces-speed", title: "5.12 Speed/Velocity & Distance/Displacement", duration: minutes(5) },
          { id: "phys-forces-acceleration", title: "5.13 Acceleration", duration: minutes(5) },
          { id: "phys-forces-distance-time", title: "5.14 Distance-time Graphs", duration: minutes(6) },
          { id: "phys-forces-velocity-time", title: "5.15 Velocity-time Graphs", duration: minutes(6) },
          { id: "phys-forces-terminal", title: "5.16 Terminal Velocity", duration: minutes(5) },
          { id: "phys-forces-newton1", title: "5.17 Newton's 1st & 2nd Laws", duration: minutes(6) },
          { id: "phys-forces-newton3", title: "5.18 Newton's 3rd Law", duration: minutes(5) },
          { id: "phys-forces-stopping", title: "5.19 Stopping Distances", duration: minutes(6) },
          { id: "phys-forces-momentum1", title: "5.20 Momentum 1", duration: minutes(5) },
          { id: "phys-forces-momentum2", title: "5.21 Momentum 2", duration: minutes(5) },
        ],
      },
      {
        id: "phys-waves",
        title: "Waves",
        description: "Wave behaviour, EM spectrum and applications with exam insight.",
        courseType: "Triple",
        tier: "Foundation",
        examBoard: "Edexcel",
        subtopics: [
          { id: "phys-waves-types", title: "6.1 Longitudinal & Transverse Waves", duration: minutes(5) },
          { id: "phys-waves-reflection", title: "6.2 Reflection", duration: minutes(5) },
          { id: "phys-waves-refraction", title: "6.3 Refraction", duration: minutes(5) },
          { id: "phys-waves-em", title: "6.4 Electromagnetic Waves", duration: minutes(6) },
          { id: "phys-waves-radio", title: "6.5 Radiowaves", duration: minutes(5) },
          { id: "phys-waves-microwave", title: "6.6 Microwaves & Infrared", duration: minutes(5) },
          { id: "phys-waves-uv", title: "6.7 UV Light", duration: minutes(5) },
          { id: "phys-waves-xray", title: "6.8 X-rays & Gamma Rays", duration: minutes(5) },
          { id: "phys-waves-lenses", title: "6.9 How Lenses Work", duration: minutes(6) },
          { id: "phys-waves-ray", title: "6.10 How to Draw Ray Diagrams", duration: minutes(6) },
          { id: "phys-waves-visible", title: "6.11 Visible Light & Colour", duration: minutes(5) },
          { id: "phys-waves-absorption", title: "6.12 Absorbing Radiation (Infrared & Black Body)", duration: minutes(5) },
          { id: "phys-waves-sound", title: "6.13 Sound Waves & Hearing", duration: minutes(5) },
          { id: "phys-waves-ultrasound", title: "6.14 Ultrasound", duration: minutes(5) },
          { id: "phys-waves-seismic", title: "6.15 Seismic Waves", duration: minutes(6) },
        ],
      },
      {
        id: "phys-magnetism",
        title: "Magnetism & Electromagnetism",
        description: "Magnets, motor effect and transformers brought to life with examples.",
        courseType: "Combined",
        tier: "Higher",
        examBoard: "OCR",
        subtopics: [
          { id: "phys-mag-magnets", title: "7.1 Magnets", duration: minutes(5) },
          { id: "phys-mag-permanent", title: "7.2 Permanent & Induced Magnets", duration: minutes(5) },
          { id: "phys-mag-electromagnetism", title: "7.3 Electromagnetism", duration: minutes(6) },
          { id: "phys-mag-motor", title: "7.4 Motor Effect", duration: minutes(5) },
          { id: "phys-mag-electric-motor", title: "7.5 How the Electric Motor Works", duration: minutes(6) },
          { id: "phys-mag-generator", title: "7.6 Generator Effect", duration: minutes(6) },
          { id: "phys-mag-alternators", title: "7.7 Alternators, Dynamos & Oscilloscopes", duration: minutes(6) },
          { id: "phys-mag-loudspeakers", title: "7.8 Loudspeakers & Microphones", duration: minutes(6) },
          { id: "phys-mag-transformers", title: "7.9 How Transformers Work", duration: minutes(6) },
          { id: "phys-mag-calculations", title: "7.10 Transformer Calculations", duration: minutes(6) },
        ],
      },
      {
        id: "phys-space",
        title: "Space Physics",
        description: "Astronomy, stellar life cycles and cosmology for triple physicists.",
        courseType: "Triple",
        tier: "Higher",
        examBoard: "AQA",
        subtopics: [
          { id: "phys-space-astronomy", title: "8.1 Astronomy - Universe, Galaxies & Solar System", duration: minutes(6) },
          { id: "phys-space-life-cycle", title: "8.2 Life Cycle of Stars", duration: minutes(6) },
          { id: "phys-space-orbits", title: "8.3 Orbits", duration: minutes(5) },
          { id: "phys-space-redshift", title: "8.4 Red Shift", duration: minutes(5) },
        ],
      },
      {
        id: "phys-practicals",
        title: "Required Practicals",
        description: "Every required physics practical with method, analysis and risk hints.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "Edexcel",
        subtopics: [
          { id: "phys-prac-shc", title: "9.1 Specific Heat Capacity", duration: minutes(6) },
          { id: "phys-prac-insulators", title: "9.2 Thermal Insulators", duration: minutes(6) },
          { id: "phys-prac-resistance", title: "9.3 Resistance of a Wire", duration: minutes(6) },
          { id: "phys-prac-iv", title: "9.4 I-V Characteristics", duration: minutes(6) },
          { id: "phys-prac-density", title: "9.5 Density", duration: minutes(6) },
          { id: "phys-prac-force", title: "9.6 Force & Extension", duration: minutes(6) },
          { id: "phys-prac-acceleration", title: "9.7 Acceleration", duration: minutes(6) },
          { id: "phys-prac-waves", title: "9.8 Waves", duration: minutes(6) },
          { id: "phys-prac-light", title: "9.9 Light", duration: minutes(6) },
          { id: "phys-prac-radiation", title: "9.10 Radiation & Absorption", duration: minutes(6) },
        ],
      },
    ],
  },
  {
    id: "english",
    name: "English Literature",
    icon: "📖",
    accent: "#f472b6",
    gradient: ["rgba(244,114,182,0.18)", "rgba(219,39,119,0.45)"],
    topics: [
      {
        id: "eng-macbeth",
        title: "Shakespeare: Macbeth",
        description: "Act-by-act analysis, themes and quotation drills for Macbeth.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "eng-macbeth-plot", title: "1.1 Plot overview and key scenes", duration: minutes(6) },
          { id: "eng-macbeth-characters", title: "1.2 Main characters and development", duration: minutes(6) },
          { id: "eng-macbeth-themes", title: "1.3 Themes: power, ambition, fate", duration: minutes(6) },
          { id: "eng-macbeth-context", title: "1.4 Context and audience", duration: minutes(5) },
          { id: "eng-macbeth-language", title: "1.5 Language and structure techniques", duration: minutes(6) },
          { id: "eng-macbeth-quotes", title: "1.6 Key quotations and analysis", duration: minutes(6) },
          { id: "eng-macbeth-irony", title: "1.7 Dramatic irony and tension", duration: minutes(5) },
          { id: "eng-macbeth-motifs", title: "1.8 Motifs and symbolism", duration: minutes(5) },
          { id: "eng-macbeth-relationships", title: "1.9 Character relationships", duration: minutes(6) },
          { id: "eng-macbeth-essays", title: "1.10 Evaluation and essay writing", duration: minutes(7) },
        ],
      },
      {
        id: "eng-romeo",
        title: "Shakespeare: Romeo and Juliet",
        description: "Tragedy structure, conflict themes and grade 9 critical lines.",
        courseType: "Triple",
        tier: "Higher",
        examBoard: "OCR",
        subtopics: [
          { id: "eng-romeo-plot", title: "1.1 Plot overview and key scenes", duration: minutes(6) },
          { id: "eng-romeo-characters", title: "1.2 Main characters and development", duration: minutes(6) },
          { id: "eng-romeo-themes", title: "1.3 Themes: love, conflict, fate", duration: minutes(6) },
          { id: "eng-romeo-context", title: "1.4 Context and audience", duration: minutes(5) },
          { id: "eng-romeo-language", title: "1.5 Language and structure techniques", duration: minutes(6) },
          { id: "eng-romeo-quotes", title: "1.6 Key quotations and analysis", duration: minutes(6) },
          { id: "eng-romeo-irony", title: "1.7 Dramatic irony and tension", duration: minutes(5) },
          { id: "eng-romeo-motifs", title: "1.8 Motifs and symbolism", duration: minutes(5) },
          { id: "eng-romeo-relationships", title: "1.9 Character relationships", duration: minutes(6) },
          { id: "eng-romeo-essays", title: "1.10 Evaluation and essay writing", duration: minutes(7) },
        ],
      },
      {
        id: "eng-christmas-carol",
        title: "19th Century: A Christmas Carol",
        description: "Dickensian context, themes and AO2 zoom-ins for Scrooge’s journey.",
        courseType: "Triple",
        tier: "Higher",
        examBoard: "Edexcel",
        subtopics: [
          { id: "eng-acc-plot", title: "2.1 Plot summary", duration: minutes(6) },
          { id: "eng-acc-scrooge", title: "2.2 Character study of Scrooge", duration: minutes(6) },
          { id: "eng-acc-themes", title: "2.3 Themes: redemption, morality", duration: minutes(6) },
          { id: "eng-acc-context", title: "2.4 Context of Victorian society", duration: minutes(5) },
          { id: "eng-acc-setting", title: "2.5 Setting and atmosphere", duration: minutes(5) },
          { id: "eng-acc-narrative", title: "2.6 Narrative perspective and structure", duration: minutes(5) },
          { id: "eng-acc-symbols", title: "2.7 Key symbols (light, transformation)", duration: minutes(5) },
          { id: "eng-acc-language", title: "2.8 Language and imagery", duration: minutes(6) },
          { id: "eng-acc-contrast", title: "2.9 Character contrasts", duration: minutes(5) },
          { id: "eng-acc-essay", title: "2.10 Practice essay planning", duration: minutes(7) },
        ],
      },
      {
        id: "eng-jekyll",
        title: "19th Century: Jekyll and Hyde",
        description: "Duality, gothic conventions and narrative voice for Stevenson’s classic.",
        courseType: "Triple",
        tier: "Higher",
        examBoard: "AQA",
        subtopics: [
          { id: "eng-jh-plot", title: "2.1 Plot summary", duration: minutes(6) },
          { id: "eng-jh-jekyll", title: "2.2 Character study of Jekyll & Hyde", duration: minutes(6) },
          { id: "eng-jh-themes", title: "2.3 Themes: duality, repression", duration: minutes(6) },
          { id: "eng-jh-context", title: "2.4 Context of Victorian society", duration: minutes(5) },
          { id: "eng-jh-setting", title: "2.5 Setting and atmosphere", duration: minutes(5) },
          { id: "eng-jh-structure", title: "2.6 Narrative perspective and structure", duration: minutes(5) },
          { id: "eng-jh-symbols", title: "2.7 Key symbols (doors, fog)", duration: minutes(5) },
          { id: "eng-jh-language", title: "2.8 Language and imagery", duration: minutes(6) },
          { id: "eng-jh-contrast", title: "2.9 Character contrasts", duration: minutes(5) },
          { id: "eng-jh-essay", title: "2.10 Practice essay planning", duration: minutes(7) },
        ],
      },
      {
        id: "eng-an-inspector-calls",
        title: "Modern Drama: An Inspector Calls",
        description: "Sheila, Gerald and the Inspector explored through structure and symbolism.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "OCR",
        subtopics: [
          { id: "eng-aic-overview", title: "3.1 Overview and act-by-act structure", duration: minutes(6) },
          { id: "eng-aic-responsibility", title: "3.2 Social responsibility and class", duration: minutes(6) },
          { id: "eng-aic-gender", title: "3.3 Gender roles and generational conflict", duration: minutes(6) },
          { id: "eng-aic-characters", title: "3.4 Character development", duration: minutes(6) },
          { id: "eng-aic-inspector", title: "3.5 The Inspector’s role and message", duration: minutes(5) },
          { id: "eng-aic-language", title: "3.6 Language and stagecraft", duration: minutes(5) },
          { id: "eng-aic-context", title: "3.7 Context: post-war Britain", duration: minutes(5) },
          { id: "eng-aic-tension", title: "3.8 Tension and dramatic devices", duration: minutes(5) },
          { id: "eng-aic-power", title: "3.9 Power dynamics", duration: minutes(5) },
          { id: "eng-aic-paragraph", title: "3.10 Model paragraph analysis", duration: minutes(6) },
        ],
      },
      {
        id: "eng-blood-brothers",
        title: "Modern Drama: Blood Brothers",
        description: "Themes of class, fate and nature vs nurture with lyric analysis.",
        courseType: "Triple",
        tier: "Foundation",
        examBoard: "Edexcel",
        subtopics: [
          { id: "eng-bb-overview", title: "3.1 Overview and act-by-act structure", duration: minutes(6) },
          { id: "eng-bb-class", title: "3.2 Social responsibility and class", duration: minutes(6) },
          { id: "eng-bb-gender", title: "3.3 Gender roles and generational conflict", duration: minutes(6) },
          { id: "eng-bb-characters", title: "3.4 Character development", duration: minutes(6) },
          { id: "eng-bb-narrator", title: "3.5 The Narrator’s role and message", duration: minutes(5) },
          { id: "eng-bb-language", title: "3.6 Language and stagecraft", duration: minutes(5) },
          { id: "eng-bb-context", title: "3.7 Context: post-war Liverpool", duration: minutes(5) },
          { id: "eng-bb-tension", title: "3.8 Tension and dramatic devices", duration: minutes(5) },
          { id: "eng-bb-power", title: "3.9 Power dynamics", duration: minutes(5) },
          { id: "eng-bb-paragraph", title: "3.10 Model paragraph analysis", duration: minutes(6) },
        ],
      },
      {
        id: "eng-power-conflict",
        title: "Poetry: Power and Conflict",
        description: "Comparative strategies, contextual nuggets and line-by-line guided reads.",
        courseType: "Combined",
        tier: "Higher",
        examBoard: "AQA",
        subtopics: [
          { id: "eng-pc-overview", title: "4.1 Overview of the anthology", duration: minutes(6) },
          { id: "eng-pc-summaries", title: "4.2 Key poem summaries", duration: minutes(6) },
          { id: "eng-pc-comparing-themes", title: "4.3 Comparing themes across poems", duration: minutes(6) },
          { id: "eng-pc-language", title: "4.4 Language and imagery analysis", duration: minutes(6) },
          { id: "eng-pc-structure", title: "4.5 Structural techniques", duration: minutes(5) },
          { id: "eng-pc-context", title: "4.6 Poet context and intent", duration: minutes(5) },
          { id: "eng-pc-emotion", title: "4.7 Conflict and emotion exploration", duration: minutes(5) },
          { id: "eng-pc-viewpoints", title: "4.8 Comparing poets’ viewpoints", duration: minutes(5) },
          { id: "eng-pc-quotes", title: "4.9 Linking quotations", duration: minutes(5) },
          { id: "eng-pc-essay", title: "4.10 Essay structure for comparison", duration: minutes(6) },
        ],
      },
      {
        id: "eng-love-relationships",
        title: "Poetry: Love and Relationships",
        description: "Tone shifts, familial love contrasts and essay comparison scaffolds.",
        courseType: "Triple",
        tier: "Higher",
        examBoard: "Edexcel",
        subtopics: [
          { id: "eng-lr-overview", title: "4.1 Overview of the anthology", duration: minutes(6) },
          { id: "eng-lr-summaries", title: "4.2 Key poem summaries", duration: minutes(6) },
          { id: "eng-lr-comparing", title: "4.3 Comparing themes across poems", duration: minutes(6) },
          { id: "eng-lr-language", title: "4.4 Language and imagery analysis", duration: minutes(6) },
          { id: "eng-lr-structure", title: "4.5 Structural techniques", duration: minutes(5) },
          { id: "eng-lr-context", title: "4.6 Poet context and intent", duration: minutes(5) },
          { id: "eng-lr-emotion", title: "4.7 Emotion and relationship exploration", duration: minutes(5) },
          { id: "eng-lr-viewpoints", title: "4.8 Comparing poets’ viewpoints", duration: minutes(5) },
          { id: "eng-lr-quotes", title: "4.9 Linking quotations", duration: minutes(5) },
          { id: "eng-lr-essay", title: "4.10 Essay structure for comparison", duration: minutes(6) },
        ],
      },
      {
        id: "eng-unseen-poetry",
        title: "Unseen Poetry Mastery",
        description: "Confidently approach unseen poems with strategic annotation and comparisons.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "OCR",
        subtopics: [
          { id: "eng-unseen-approach", title: "5.1 How to approach unseen poetry", duration: minutes(6) },
          { id: "eng-unseen-tone", title: "5.2 Identifying tone, theme, and structure", duration: minutes(6) },
          { id: "eng-unseen-annotate", title: "5.3 Annotating effectively", duration: minutes(6) },
          { id: "eng-unseen-language", title: "5.4 Analysing language and form", duration: minutes(6) },
          { id: "eng-unseen-compare", title: "5.5 Comparing unseen poems", duration: minutes(6) },
          { id: "eng-unseen-timed", title: "5.6 Practising timed responses", duration: minutes(5) },
          { id: "eng-unseen-techniques", title: "5.7 Common poetic techniques", duration: minutes(5) },
          { id: "eng-unseen-vocab", title: "5.8 Vocabulary for analysis", duration: minutes(5) },
          { id: "eng-unseen-writing", title: "5.9 Writing comparisons", duration: minutes(6) },
          { id: "eng-unseen-model", title: "5.10 Model unseen essay breakdown", duration: minutes(7) },
        ],
      },
    ],
  },
  {
    id: "business",
    name: "Business Studies",
    icon: "💼",
    accent: "#22c55e",
    gradient: ["rgba(34,197,94,0.16)", "rgba(5,150,105,0.42)"],
    topics: [
      {
        id: "bus-real-world",
        title: "Business in the Real World",
        description: "Enterprise, aims and the realities of launching a startup.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "bus-real-purpose", title: "1.1 Purpose & nature of business", duration: minutes(6) },
          { id: "bus-real-enterprise", title: "1.2 Enterprise & entrepreneurship", duration: minutes(6) },
          { id: "bus-real-aims", title: "1.3 Business aims & objectives", duration: minutes(6) },
          { id: "bus-real-stakeholders", title: "1.4 Stakeholders", duration: minutes(5) },
          { id: "bus-real-ownership", title: "1.5 Business ownership types", duration: minutes(6) },
          { id: "bus-real-growth", title: "1.6 Growth & integration", duration: minutes(6) },
          { id: "bus-real-planning", title: "1.7 Business planning", duration: minutes(6) },
          { id: "bus-real-risk", title: "1.8 Risk & uncertainty", duration: minutes(5) },
          { id: "bus-real-environment", title: "1.9 Changing business environment", duration: minutes(6) },
          { id: "bus-real-technology", title: "1.10 Role of technology", duration: minutes(5) },
        ],
      },
      {
        id: "bus-influences",
        title: "Influences on Business",
        description: "Economic shifts, ethics and globalisation on business decisions.",
        courseType: "Triple",
        tier: "Higher",
        examBoard: "Edexcel",
        subtopics: [
          { id: "bus-inf-economic", title: "2.1 Economic influences", duration: minutes(6) },
          { id: "bus-inf-ethical", title: "2.2 Environmental & ethical issues", duration: minutes(6) },
          { id: "bus-inf-globalisation", title: "2.3 Globalisation", duration: minutes(6) },
          { id: "bus-inf-legislation", title: "2.4 Legislation", duration: minutes(5) },
          { id: "bus-inf-competition", title: "2.5 Competition & market changes", duration: minutes(6) },
          { id: "bus-inf-innovation", title: "2.6 Technological innovation", duration: minutes(5) },
          { id: "bus-inf-rates", title: "2.7 Interest rates & exchange rates", duration: minutes(6) },
          { id: "bus-inf-inflation", title: "2.8 Inflation & unemployment", duration: minutes(6) },
          { id: "bus-inf-pressures", title: "2.9 External pressures", duration: minutes(5) },
          { id: "bus-inf-policy", title: "2.10 Government policy", duration: minutes(5) },
        ],
      },
      {
        id: "bus-operations",
        title: "Business Operations",
        description: "Production, logistics and service quality with modern examples.",
        courseType: "Combined",
        tier: "Higher",
        examBoard: "OCR",
        subtopics: [
          { id: "bus-ops-production", title: "3.1 Production processes", duration: minutes(6) },
          { id: "bus-ops-quality", title: "3.2 Quality control & assurance", duration: minutes(6) },
          { id: "bus-ops-lean", title: "3.3 Lean production", duration: minutes(6) },
          { id: "bus-ops-supply", title: "3.4 Supply chains", duration: minutes(5) },
          { id: "bus-ops-service", title: "3.5 Customer service", duration: minutes(6) },
          { id: "bus-ops-technology", title: "3.6 Technology in operations", duration: minutes(5) },
          { id: "bus-ops-logistics", title: "3.7 Logistics & procurement", duration: minutes(6) },
          { id: "bus-ops-stock", title: "3.8 Stock control", duration: minutes(6) },
          { id: "bus-ops-efficiency", title: "3.9 Efficiency improvements", duration: minutes(6) },
          { id: "bus-ops-sustainability", title: "3.10 Sustainability in production", duration: minutes(6) },
        ],
      },
      {
        id: "bus-human-resources",
        title: "Human Resources",
        description: "Recruitment, motivation and workforce planning essentials.",
        courseType: "Triple",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "bus-hr-structures", title: "4.1 Organisational structures", duration: minutes(6) },
          { id: "bus-hr-communication", title: "4.2 Communication in business", duration: minutes(6) },
          { id: "bus-hr-recruitment", title: "4.3 Recruitment & selection", duration: minutes(6) },
          { id: "bus-hr-training", title: "4.4 Training & development", duration: minutes(6) },
          { id: "bus-hr-motivation", title: "4.5 Motivation & financial incentives", duration: minutes(6) },
          { id: "bus-hr-non-financial", title: "4.6 Non-financial motivation methods", duration: minutes(5) },
          { id: "bus-hr-law", title: "4.7 Employment law", duration: minutes(5) },
          { id: "bus-hr-appraisal", title: "4.8 Appraisal & performance", duration: minutes(6) },
          { id: "bus-hr-workforce", title: "4.9 Workforce planning", duration: minutes(6) },
          { id: "bus-hr-unions", title: "4.10 Trade unions", duration: minutes(5) },
        ],
      },
      {
        id: "bus-marketing",
        title: "Marketing",
        description: "Market research, the mix and digital-first campaign planning.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "Edexcel",
        subtopics: [
          { id: "bus-mkt-research", title: "5.1 Market research & segmentation", duration: minutes(6) },
          { id: "bus-mkt-product", title: "5.2 Product design & differentiation", duration: minutes(6) },
          { id: "bus-mkt-pricing", title: "5.3 Pricing strategies", duration: minutes(6) },
          { id: "bus-mkt-promotion", title: "5.4 Promotion & advertising", duration: minutes(6) },
          { id: "bus-mkt-place", title: "5.5 Place & distribution", duration: minutes(5) },
          { id: "bus-mkt-mix", title: "5.6 Marketing mix integration", duration: minutes(5) },
          { id: "bus-mkt-digital", title: "5.7 Digital marketing", duration: minutes(6) },
          { id: "bus-mkt-branding", title: "5.8 Branding & reputation", duration: minutes(5) },
          { id: "bus-mkt-life-cycle", title: "5.9 Product life cycle", duration: minutes(5) },
          { id: "bus-mkt-extension", title: "5.10 Extension strategies", duration: minutes(6) },
        ],
      },
      {
        id: "bus-finance",
        title: "Finance",
        description: "Cash flow, forecasting and financial decision making for GCSE success.",
        courseType: "Triple",
        tier: "Higher",
        examBoard: "OCR",
        subtopics: [
          { id: "bus-fin-sources", title: "6.1 Sources of finance", duration: minutes(6) },
          { id: "bus-fin-calculations", title: "6.2 Revenue, cost & profit calculations", duration: minutes(6) },
          { id: "bus-fin-cashflow", title: "6.3 Cash flow", duration: minutes(6) },
          { id: "bus-fin-breakeven", title: "6.4 Breakeven analysis", duration: minutes(6) },
          { id: "bus-fin-documents", title: "6.5 Financial documents", duration: minutes(5) },
          { id: "bus-fin-ratios", title: "6.6 Ratios & performance indicators", duration: minutes(6) },
          { id: "bus-fin-budgeting", title: "6.7 Budgeting", duration: minutes(6) },
          { id: "bus-fin-forecasting", title: "6.8 Financial forecasting", duration: minutes(6) },
          { id: "bus-fin-investment", title: "6.9 Investment decisions", duration: minutes(6) },
          { id: "bus-fin-impact", title: "6.10 Impact of financial performance", duration: minutes(6) },
        ],
      },
    ],
  },
  {
    id: "geography",
    name: "Geography",
    icon: "🌍",
    accent: "#8b5cf6",
    gradient: ["rgba(139,92,246,0.18)", "rgba(99,102,241,0.42)"],
    topics: [
      {
        id: "geo-natural-hazards",
        title: "Natural Hazards",
        description: "Plate tectonics, climate hazards and climate change responses.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "geo-hazards-plate", title: "1.1 Plate tectonics theory", duration: minutes(6) },
          { id: "geo-hazards-earthquakes", title: "1.2 Earthquakes and volcanoes", duration: minutes(6) },
          { id: "geo-hazards-weather", title: "1.3 Weather hazards", duration: minutes(6) },
          { id: "geo-hazards-tropical", title: "1.4 Tropical storms", duration: minutes(6) },
          { id: "geo-hazards-climate", title: "1.5 Climate change causes and effects", duration: minutes(6) },
          { id: "geo-hazards-risk", title: "1.6 Reducing risk from hazards", duration: minutes(6) },
          { id: "geo-hazards-case", title: "1.7 Case studies (HIC vs LIC)", duration: minutes(7) },
          { id: "geo-hazards-circulation", title: "1.8 Global atmospheric circulation", duration: minutes(5) },
          { id: "geo-hazards-impacts", title: "1.9 Impacts and responses", duration: minutes(5) },
          { id: "geo-hazards-managing", title: "1.10 Managing climate change", duration: minutes(6) },
        ],
      },
      {
        id: "geo-living-world",
        title: "The Living World",
        description: "Ecosystems, tropical rainforests and hot desert challenges.",
        courseType: "Triple",
        tier: "Higher",
        examBoard: "Edexcel",
        subtopics: [
          { id: "geo-living-ecosystems", title: "2.1 Ecosystems and nutrient cycles", duration: minutes(6) },
          { id: "geo-living-rainforests", title: "2.2 Tropical rainforests", duration: minutes(6) },
          { id: "geo-living-adaptations", title: "2.3 Adaptations of plants and animals", duration: minutes(6) },
          { id: "geo-living-deforestation", title: "2.4 Deforestation causes and impacts", duration: minutes(6) },
          { id: "geo-living-sustainable", title: "2.5 Sustainable rainforest management", duration: minutes(6) },
          { id: "geo-living-hot-desert", title: "2.6 Hot desert ecosystems", duration: minutes(6) },
          { id: "geo-living-desertification", title: "2.7 Desertification", duration: minutes(6) },
          { id: "geo-living-opportunities", title: "2.8 Opportunities in desert regions", duration: minutes(5) },
          { id: "geo-living-case", title: "2.9 Case study: Thar Desert", duration: minutes(5) },
          { id: "geo-living-management", title: "2.10 Desert management strategies", duration: minutes(6) },
        ],
      },
      {
        id: "geo-uk-landscapes",
        title: "UK Physical Landscapes",
        description: "Coasts, rivers and glacial landscapes with fieldwork-ready skills.",
        courseType: "Combined",
        tier: "Higher",
        examBoard: "OCR",
        subtopics: [
          { id: "geo-uk-coasts", title: "3.1 Coastal processes", duration: minutes(6) },
          { id: "geo-uk-landforms", title: "3.2 Landforms of erosion and deposition", duration: minutes(6) },
          { id: "geo-uk-coastal-management", title: "3.3 Coastal management strategies", duration: minutes(6) },
          { id: "geo-uk-river-processes", title: "3.4 River processes", duration: minutes(6) },
          { id: "geo-uk-river-landforms", title: "3.5 River landforms and profiles", duration: minutes(6) },
          { id: "geo-uk-flooding", title: "3.6 Flooding causes and impacts", duration: minutes(6) },
          { id: "geo-uk-flood-management", title: "3.7 Flood management", duration: minutes(6) },
          { id: "geo-uk-case", title: "3.8 River case studies", duration: minutes(6) },
          { id: "geo-uk-glacial", title: "3.9 Glacial landscapes (optional)", duration: minutes(5) },
          { id: "geo-uk-fieldwork", title: "3.10 Fieldwork skills", duration: minutes(6) },
        ],
      },
      {
        id: "geo-urban-issues",
        title: "Urban Issues and Challenges",
        description: "Urbanisation, megacities and sustainable planning case studies.",
        courseType: "Triple",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "geo-urban-urbanisation", title: "4.1 Urbanisation and megacities", duration: minutes(6) },
          { id: "geo-urban-growth", title: "4.2 Causes of urban growth", duration: minutes(6) },
          { id: "geo-urban-uk", title: "4.3 Urban change in the UK", duration: minutes(6) },
          { id: "geo-urban-lic", title: "4.4 Opportunities and challenges in LIC cities", duration: minutes(6) },
          { id: "geo-urban-rio", title: "4.5 Rio de Janeiro case study", duration: minutes(6) },
          { id: "geo-urban-sustainable", title: "4.6 Sustainable urban planning", duration: minutes(6) },
          { id: "geo-urban-london", title: "4.7 London regeneration case study", duration: minutes(6) },
          { id: "geo-urban-transport", title: "4.8 Transport and housing solutions", duration: minutes(5) },
          { id: "geo-urban-environment", title: "4.9 Environmental challenges", duration: minutes(5) },
          { id: "geo-urban-inequality", title: "4.10 Urban inequality", duration: minutes(6) },
        ],
      },
      {
        id: "geo-economic-world",
        title: "The Changing Economic World",
        description: "Development indicators, the UK economy and globalisation impacts.",
        courseType: "Combined",
        tier: "Higher",
        examBoard: "Edexcel",
        subtopics: [
          { id: "geo-econ-measure", title: "5.1 Measuring development", duration: minutes(6) },
          { id: "geo-econ-inequality", title: "5.2 Causes of global inequality", duration: minutes(6) },
          { id: "geo-econ-gap", title: "5.3 Reducing the development gap", duration: minutes(6) },
          { id: "geo-econ-nee", title: "5.4 Economic growth in NEEs (Nigeria)", duration: minutes(6) },
          { id: "geo-econ-uk", title: "5.5 The UK economy in change", duration: minutes(6) },
          { id: "geo-econ-globalisation", title: "5.6 Globalisation impacts", duration: minutes(6) },
          { id: "geo-econ-employment", title: "5.7 Employment sectors", duration: minutes(5) },
          { id: "geo-econ-post-industrial", title: "5.8 The post-industrial economy", duration: minutes(5) },
          { id: "geo-econ-environment", title: "5.9 Environmental impacts of industry", duration: minutes(5) },
          { id: "geo-econ-sustainable", title: "5.10 Sustainable development", duration: minutes(6) },
        ],
      },
      {
        id: "geo-resource-management",
        title: "Resource Management",
        description: "Food, water and energy security in the UK and globally.",
        courseType: "Triple",
        tier: "Foundation",
        examBoard: "OCR",
        subtopics: [
          { id: "geo-resource-importance", title: "6.1 Importance of food, water, and energy", duration: minutes(6) },
          { id: "geo-resource-inequalities", title: "6.2 Global inequalities in resources", duration: minutes(6) },
          { id: "geo-resource-food", title: "6.3 Food supply and demand", duration: minutes(6) },
          { id: "geo-resource-water", title: "6.4 Water scarcity and management", duration: minutes(6) },
          { id: "geo-resource-energy", title: "6.5 Energy resources and consumption", duration: minutes(6) },
          { id: "geo-resource-renewable", title: "6.6 Renewable vs non-renewable", duration: minutes(6) },
          { id: "geo-resource-uk", title: "6.7 UK resource management", duration: minutes(5) },
          { id: "geo-resource-food-strategies", title: "6.8 Sustainable food strategies", duration: minutes(6) },
          { id: "geo-resource-energy-alternatives", title: "6.9 Energy alternatives", duration: minutes(5) },
          { id: "geo-resource-case", title: "6.10 Case studies of sustainable management", duration: minutes(6) },
        ],
      },
      {
        id: "geo-skills",
        title: "Geographical Skills & Fieldwork",
        description: "Map skills, data presentation and exam-style evaluation techniques.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "AQA",
        subtopics: [
          { id: "geo-skills-os", title: "7.1 OS map skills", duration: minutes(6) },
          { id: "geo-skills-graphs", title: "7.2 Graphs and data interpretation", duration: minutes(6) },
          { id: "geo-skills-planning", title: "7.3 Fieldwork planning and risk assessment", duration: minutes(6) },
          { id: "geo-skills-data", title: "7.4 Data collection techniques", duration: minutes(6) },
          { id: "geo-skills-human", title: "7.5 Human geography fieldwork", duration: minutes(6) },
          { id: "geo-skills-physical", title: "7.6 Physical geography fieldwork", duration: minutes(6) },
          { id: "geo-skills-presentation", title: "7.7 Data presentation", duration: minutes(6) },
          { id: "geo-skills-evaluation", title: "7.8 Evaluation and conclusions", duration: minutes(6) },
          { id: "geo-skills-sampling", title: "7.9 Sampling methods", duration: minutes(5) },
          { id: "geo-skills-exam", title: "7.10 Exam question practice", duration: minutes(6) },
        ],
      },
    ],
  },
  {
    id: "history",
    name: "History",
    icon: "📜",
    accent: "#facc15",
    gradient: ["rgba(250,204,21,0.2)", "rgba(245,158,11,0.45)"],
    topics: [
      {
        id: "hist-medicine",
        title: "Medicine Through Time",
        description: "From prehistoric remedies to the NHS with source analysis tips.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "Edexcel",
        subtopics: [
          { id: "hist-med-prehistoric", title: "1.1 Prehistoric and Ancient medicine", duration: minutes(6) },
          { id: "hist-med-medieval", title: "1.2 Medieval medicine and the Black Death", duration: minutes(6) },
          { id: "hist-med-renaissance", title: "1.3 Renaissance discoveries", duration: minutes(6) },
          { id: "hist-med-18th", title: "1.4 18th and 19th century improvements", duration: minutes(6) },
          { id: "hist-med-germ", title: "1.5 Germ theory and Pasteur", duration: minutes(5) },
          { id: "hist-med-modern", title: "1.6 Modern medicine and the NHS", duration: minutes(6) },
          { id: "hist-med-public", title: "1.7 Public health development", duration: minutes(5) },
          { id: "hist-med-surgery", title: "1.8 Surgery through time", duration: minutes(6) },
          { id: "hist-med-jenner", title: "1.9 Case study: Jenner and vaccination", duration: minutes(5) },
          { id: "hist-med-factors", title: "1.10 Factors influencing change", duration: minutes(6) },
        ],
      },
      {
        id: "hist-elizabethan",
        title: "Elizabethan England",
        description: "Elizabeth’s reign, plots and exploration set within Tudor politics.",
        courseType: "Combined",
        tier: "Higher",
        examBoard: "OCR",
        subtopics: [
          { id: "hist-eliz-early", title: "2.1 Elizabeth’s early reign", duration: minutes(6) },
          { id: "hist-eliz-religious", title: "2.2 Religious settlement", duration: minutes(6) },
          { id: "hist-eliz-plots", title: "2.3 Plots and rebellions", duration: minutes(6) },
          { id: "hist-eliz-mary", title: "2.4 Mary Queen of Scots", duration: minutes(6) },
          { id: "hist-eliz-armada", title: "2.5 The Spanish Armada", duration: minutes(6) },
          { id: "hist-eliz-poverty", title: "2.6 Poverty and social change", duration: minutes(5) },
          { id: "hist-eliz-exploration", title: "2.7 Exploration and Drake", duration: minutes(6) },
          { id: "hist-eliz-theatre", title: "2.8 Theatre and culture", duration: minutes(5) },
          { id: "hist-eliz-court", title: "2.9 Court and government", duration: minutes(5) },
          { id: "hist-eliz-local", title: "2.10 Local case study", duration: minutes(5) },
        ],
      },
      {
        id: "hist-weimar",
        title: "Weimar and Nazi Germany",
        description: "Weimar challenges, Nazi control and opposition with thematic revision.",
        courseType: "Combined",
        tier: "Higher",
        examBoard: "AQA",
        subtopics: [
          { id: "hist-weimar-creation", title: "3.1 The Weimar Republic’s creation", duration: minutes(6) },
          { id: "hist-weimar-challenges", title: "3.2 Challenges and hyperinflation", duration: minutes(6) },
          { id: "hist-weimar-hitler", title: "3.3 Hitler’s rise to power", duration: minutes(6) },
          { id: "hist-weimar-propaganda", title: "3.4 Propaganda and control", duration: minutes(6) },
          { id: "hist-weimar-police", title: "3.5 The police state and censorship", duration: minutes(6) },
          { id: "hist-weimar-life", title: "3.6 Women, youth, and education", duration: minutes(6) },
          { id: "hist-weimar-holocaust", title: "3.7 The Holocaust", duration: minutes(6) },
          { id: "hist-weimar-opposition", title: "3.8 Opposition and resistance", duration: minutes(6) },
          { id: "hist-weimar-economy", title: "3.9 Nazi economy and employment", duration: minutes(6) },
          { id: "hist-weimar-ww2", title: "3.10 Germany in WWII", duration: minutes(6) },
        ],
      },
      {
        id: "hist-cold-war",
        title: "The Cold War",
        description: "Origins, flashpoints and the fall of the USSR with timeline memory aids.",
        courseType: "Triple",
        tier: "Foundation",
        examBoard: "Edexcel",
        subtopics: [
          { id: "hist-cold-origins", title: "4.1 Origins of the Cold War", duration: minutes(6) },
          { id: "hist-cold-ideology", title: "4.2 Ideological differences", duration: minutes(6) },
          { id: "hist-cold-berlin", title: "4.3 Berlin Blockade & Airlift", duration: minutes(6) },
          { id: "hist-cold-cuba", title: "4.4 Cuban Missile Crisis", duration: minutes(6) },
          { id: "hist-cold-vietnam", title: "4.5 Vietnam War", duration: minutes(6) },
          { id: "hist-cold-eastern", title: "4.6 Soviet control in Eastern Europe", duration: minutes(6) },
          { id: "hist-cold-detente", title: "4.7 Détente and arms race", duration: minutes(6) },
          { id: "hist-cold-fall", title: "4.8 Fall of the Berlin Wall", duration: minutes(6) },
          { id: "hist-cold-end", title: "4.9 End of the USSR", duration: minutes(6) },
          { id: "hist-cold-legacy", title: "4.10 Legacy of the Cold War", duration: minutes(6) },
        ],
      },
      {
        id: "hist-conflict",
        title: "Conflict and Tension",
        description: "WWI causes to post-war cooperation with source-friendly summaries.",
        courseType: "Combined",
        tier: "Foundation",
        examBoard: "OCR",
        subtopics: [
          { id: "hist-conflict-causes", title: "5.1 Causes of WWI", duration: minutes(6) },
          { id: "hist-conflict-trench", title: "5.2 Trench warfare", duration: minutes(6) },
          { id: "hist-conflict-versailles", title: "5.3 Treaty of Versailles", duration: minutes(6) },
          { id: "hist-conflict-league", title: "5.4 League of Nations", duration: minutes(6) },
          { id: "hist-conflict-appeasement", title: "5.5 Appeasement and Hitler’s aggression", duration: minutes(6) },
          { id: "hist-conflict-outbreak", title: "5.6 Outbreak of WWII", duration: minutes(6) },
          { id: "hist-conflict-allies", title: "5.7 The role of the Allies", duration: minutes(6) },
          { id: "hist-conflict-consequences", title: "5.8 Consequences of conflict", duration: minutes(6) },
          { id: "hist-conflict-cooperation", title: "5.9 International cooperation post-war", duration: minutes(6) },
          { id: "hist-conflict-case", title: "5.10 Case study analysis", duration: minutes(6) },
        ],
      },
      {
        id: "hist-skills",
        title: "Historical Skills",
        description: "Source analysis, interpretation and exam writing frameworks.",
        courseType: "Triple",
        tier: "Higher",
        examBoard: "AQA",
        subtopics: [
          { id: "hist-skills-source", title: "6.1 Source analysis (content, provenance)", duration: minutes(6) },
          { id: "hist-skills-reliability", title: "6.2 Interpreting reliability and bias", duration: minutes(6) },
          { id: "hist-skills-comparing", title: "6.3 Comparing interpretations", duration: minutes(6) },
          { id: "hist-skills-chronology", title: "6.4 Chronology and causation", duration: minutes(6) },
          { id: "hist-skills-significance", title: "6.5 Significance and consequence", duration: minutes(6) },
          { id: "hist-skills-paragraphs", title: "6.6 Writing analytical paragraphs", duration: minutes(6) },
          { id: "hist-skills-structure", title: "6.7 Essay structure (PEEL/PEARL)", duration: minutes(6) },
          { id: "hist-skills-evidence", title: "6.8 Using evidence effectively", duration: minutes(6) },
          { id: "hist-skills-context", title: "6.9 Linking context and events", duration: minutes(6) },
          { id: "hist-skills-evaluation", title: "6.10 Evaluation and judgment", duration: minutes(6) },
        ],
      },
    ],
  }
];
